### ISSUE TITLE
Ikari Warriors problem on MRA

### ISSUE THREAD

**Issue by theypsilon** [MiSTer-devel/Arcade-IkariWarriors_MiSTer#1]
He tenido que quitar la siguiente linea de la wiki de MiSTer_Main:

```
* [Ikari Warriors](https://github.com/MiSTer-devel/Arcade-IkariWarriors_MiSTer) Inc: Ikari JP, Victory Road, Dogou Souken
```

La razón es que el XML contenía un bug, y XMLs incorrectos impiden la distribución de binarios de todos los cores. Para solucionarlo, por favor usa un validador de XML online cualquiera. Allí se te indicará qué parte del XML es inválido para que puedas corregirlo.

¡Muchas gracias!

**Comment by RndMnkIII** [comment]
He corregido el error en:
https://github.com/MiSTer-devel/Main_MiSTer/wiki/Arcade-Cores-List
Funciona correctamente, siento que esto haya podido ocasionar algún contratiempo.

**Comment by theypsilon** [comment]
Este archivo es el que causa el problema y todavía no está corregido: https://github.com/MiSTer-devel/Arcade-IkariWarriors_MiSTer/blob/main/releases/Ikari%20Warriors.mra

Si lo compruebas aquí verás que hay un error: https://www.xmlvalidation.com/

Mientras haya error en ese XML, la distribución de binarios se romperá, por tanto voy a quitar esa lína de Arcade-Cores-List otra vez mientras tanto.

**Comment by RndMnkIII** [comment]
ok, o sea que es el propio mra, ahora mismo lo miro

**Comment by RndMnkIII** [comment]
vale estaba usando el caracter ampersand en una cadena, he probado con una sequencia de escape pero me da error al validar tambien el xml, así que lo he sustituido por 'and'. Ya esta actualizado el repositorio con los cambios a los mra. Ahora no deberia fallar.

**Comment by theypsilon** [comment]
Muchas gracias, ya he vuelto a poner la línea en la wiki y todo debería descargarse nuevamente.
